# Generated by Django 5.1.15 on 2026-01-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='duration (minutes)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price')),
                ('requires_fasting', models.BooleanField(default=False, verbose_name='requires fasting')),
                ('preparation_instructions', models.TextField(blank=True, verbose_name='preparation instructions')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='clinics.clinic', verbose_name='clinic')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ['clinic', 'name'],
                'unique_together': {('clinic', 'slug')},
            },
        ),
    ]
