# Generated by Django 5.2.11 on 2026-02-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='service',
            name='preparation_instructions_ar',
            field=models.TextField(blank=True, null=True, verbose_name='preparation instructions'),
        ),
        migrations.AddField(
            model_name='service',
            name='preparation_instructions_en',
            field=models.TextField(blank=True, null=True, verbose_name='preparation instructions'),
        ),
    ]
