# Generated by Django 5.1.15 on 2026-01-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clinic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('logo', models.ImageField(blank=True, upload_to='clinics/logos/', verbose_name='logo')),
                ('cover_image', models.ImageField(blank=True, upload_to='clinics/covers/', verbose_name='cover image')),
                ('opening_time', models.TimeField(default='08:00', verbose_name='opening time')),
                ('closing_time', models.TimeField(default='20:00', verbose_name='closing time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='total reviews')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'clinic',
                'verbose_name_plural': 'clinics',
                'ordering': ['-rating', 'name'],
                'indexes': [models.Index(fields=['slug'], name='clinics_cli_slug_c0ea0f_idx'), models.Index(fields=['city'], name='clinics_cli_city_d5aa71_idx'), models.Index(fields=['-rating'], name='clinics_cli_rating_e3a732_idx')],
            },
        ),
    ]
