# Generated by Django 5.1.15 on 2026-02-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinic',
            name='address_ar',
            field=models.TextField(null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='address_en',
            field=models.TextField(null=True, verbose_name='address'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='description_ar',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='name_ar',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='clinic',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
    ]
