# Generated by Django 5.1.15 on 2026-01-20 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('reason', models.CharField(blank=True, max_length=200, verbose_name='reason')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='recurring annually')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'day off',
                'verbose_name_plural': 'days off',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='slug')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'specialization',
                'verbose_name_plural': 'specializations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Sunday'), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday')], verbose_name='day of week')),
                ('start_time', models.TimeField(verbose_name='start time')),
                ('end_time', models.TimeField(verbose_name='end time')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'working hour',
                'verbose_name_plural': 'working hours',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=50, unique=True, verbose_name='license number')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='years of experience')),
                ('education', models.TextField(blank=True, verbose_name='education')),
                ('bio', models.TextField(verbose_name='biography')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='consultation fee')),
                ('total_patients', models.PositiveIntegerField(default=0, verbose_name='total patients')),
                ('rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='total reviews')),
                ('is_available', models.BooleanField(default=True, verbose_name='available')),
                ('is_verified', models.BooleanField(default=False, verbose_name='verified')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctors', to='clinics.clinic', verbose_name='clinic')),
            ],
            options={
                'verbose_name': 'doctor',
                'verbose_name_plural': 'doctors',
                'ordering': ['-rating', 'user__first_name'],
            },
        ),
    ]
