# Generated by Django 5.1.15 on 2026-01-20 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days_off', to='doctors.doctor', verbose_name='doctor'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='specialization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='doctors', to='doctors.specialization', verbose_name='specialization'),
        ),
        migrations.AddField(
            model_name='workinghour',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='doctors.doctor', verbose_name='doctor'),
        ),
        migrations.AddIndex(
            model_name='dayoff',
            index=models.Index(fields=['doctor', 'date'], name='doctors_day_doctor__7b7f4d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dayoff',
            unique_together={('doctor', 'date')},
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['clinic', 'specialization'], name='doctors_doc_clinic__9e138b_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['-rating'], name='doctors_doc_rating_042358_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_available'], name='doctors_doc_is_avai_e473c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='workinghour',
            unique_together={('doctor', 'day_of_week', 'start_time')},
        ),
    ]
