# Generated by Django 5.2.11 on 2026-02-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bio_ar',
            field=models.TextField(null=True, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='bio_en',
            field=models.TextField(null=True, verbose_name='biography'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_ar',
            field=models.TextField(blank=True, null=True, verbose_name='education'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='education_en',
            field=models.TextField(blank=True, null=True, verbose_name='education'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='name_ar',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='specialization',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
