# Generated by Django 5.1.15 on 2026-01-28 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_initial'),
        ('clinics', '0001_initial'),
        ('doctors', '0002_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('VISA', 'Visa Card'), ('MASTERCARD', 'Mastercard'), ('CASH', 'Cash'), ('INSURANCE', 'Insurance')], default='VISA', max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20, verbose_name='status')),
                ('card_last_four', models.CharField(blank=True, help_text='Last 4 digits of card', max_length=4, verbose_name='card last 4 digits')),
                ('card_brand', models.CharField(blank=True, max_length=20, verbose_name='card brand')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='transaction ID')),
                ('gateway_response', models.JSONField(blank=True, help_text='Payment gateway response data', null=True, verbose_name='gateway response')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='base amount')),
                ('cancellation_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cancellation fee')),
                ('late_fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='late payment fee')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('is_refunded', models.BooleanField(default=False, verbose_name='is refunded')),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='refund amount')),
                ('refunded_at', models.DateTimeField(blank=True, null=True, verbose_name='refunded at')),
                ('refund_reason', models.TextField(blank=True, verbose_name='refund reason')),
            ],
            options={
                'verbose_name': 'payment',
                'verbose_name_plural': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_token', models.CharField(help_text='Tokenized card from payment gateway', max_length=255, verbose_name='card token')),
                ('card_last_four', models.CharField(max_length=4, verbose_name='last 4 digits')),
                ('card_brand', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'Mastercard'), ('amex', 'American Express')], max_length=20, verbose_name='card brand')),
                ('expiry_month', models.CharField(max_length=2, verbose_name='expiry month')),
                ('expiry_year', models.CharField(max_length=4, verbose_name='expiry year')),
                ('cardholder_name', models.CharField(max_length=255, verbose_name='cardholder name')),
                ('is_default', models.BooleanField(default=False, verbose_name='is default')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'payment card',
                'verbose_name_plural': 'payment cards',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_appointment_slot',
        ),
        migrations.AddField(
            model_name='appointment',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Original appointment price', max_digits=10, verbose_name='base price'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fee charged for late cancellation', max_digits=10, verbose_name='cancellation fee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is paid'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='late_payment_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional fee for late payment', max_digits=10, verbose_name='late payment fee'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='paid at'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_due_date',
            field=models.DateTimeField(blank=True, help_text='Payment must be made before this date', null=True, verbose_name='payment due date'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount to pay', max_digits=10, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='end time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='services.service', verbose_name='service'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['is_paid'], name='appointment_is_paid_e1253f_idx'),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['PENDING', 'CONFIRMED'])), fields=('doctor', 'date', 'start_time'), name='unique_doctor_appointment_slot'),
        ),
        migrations.AddField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.appointment', verbose_name='appointment'),
        ),
        migrations.AddField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='patient'),
        ),
        migrations.AddField(
            model_name='paymentcard',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL, verbose_name='patient'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['appointment', 'status'], name='appointment_appoint_188ddf_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['patient', '-created_at'], name='appointment_patient_038792_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='appointment_status_a3afba_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['-created_at'], name='appointment_created_880aec_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentcard',
            index=models.Index(fields=['patient', 'is_active'], name='appointment_patient_4c961c_idx'),
        ),
    ]
