# Generated by Django 5.1.15 on 2026-01-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_payment_paymentcard_and_more'),
    ]

    operations = [
    ]
