# Generated by Django 5.1.15 on 2026-02-08 15:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20260128_1733'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='paymentcard',
            options={'ordering': ['-is_default', '-created_at']},
        ),
        migrations.RemoveConstraint(
            model_name='appointment',
            name='unique_doctor_appointment_slot',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_clinic__f6186d_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_created_b22799_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='appointment_appoint_188ddf_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='appointment_patient_038792_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='appointment_status_a3afba_idx',
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='appointment_created_880aec_idx',
        ),
        migrations.RemoveIndex(
            model_name='paymentcard',
            name='appointment_patient_4c961c_idx',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='base price'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='cancellation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='cancellation fee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='late_payment_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='late payment fee'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment_due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='payment due date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total amount'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.appointment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='base_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='cancellation_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_last_four',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='payment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='gateway_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='is_refunded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='payment',
            name='late_fee_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('VISA', 'Visa'), ('MASTERCARD', 'Mastercard'), ('CASH', 'Cash')], default='VISA', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_brand',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_last_four',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='card_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='cardholder_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='expiry_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='expiry_year',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='paymentcard',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
