# Generated by Django 5.1.15 on 2026-02-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_payment_options_alter_paymentcard_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason_ar',
            field=models.TextField(blank=True, null=True, verbose_name='cancellation reason'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancellation_reason_en',
            field=models.TextField(blank=True, null=True, verbose_name='cancellation reason'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes_ar',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='notes_en',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms_ar',
            field=models.TextField(blank=True, null=True, verbose_name='symptoms'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='symptoms_en',
            field=models.TextField(blank=True, null=True, verbose_name='symptoms'),
        ),
    ]
